version: '4'
services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    command: python src/main.py
